server:
  port: 8081

logging:
  level:
    org.springframework.web: trace
spring:
  datasource:
    url: jdbc:h2:file:~/testdb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
  h2:
    console.enabled: true